# Generated by Django 4.1.7 on 2023-03-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signup", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffprofile",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "Active"),
                    (2, "Terminate"),
                    (3, "Resign"),
                    (4, "Alumni"),
                    (5, "Other STAFF Status"),
                ],
                default=1,
            ),
        ),
    ]
