# Generated by Django 4.1.7 on 2023-03-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signup", "0002_alter_staffprofile_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffprofile",
            name="first_login",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
