# Generated by Django 4.1.7 on 2023-04-15 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("signup", "0004_divisi_staffprofile_divisi"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaSosial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama_media", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Media Sosial",
                "verbose_name_plural": "Media Sosial",
            },
        ),
        migrations.CreateModel(
            name="ProfileImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "verbose_name": "Profile Image",
                "verbose_name_plural": "Profile Image",
            },
        ),
        migrations.CreateModel(
            name="StaffMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("akun", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "medsos",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="signup.mediasosial",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="signup.staffprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "StaffMedia",
                "verbose_name_plural": "StaffMedia",
            },
        ),
        migrations.CreateModel(
            name="InfoDirektur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("appresiasi", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "spesialisasi",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="signup.staffprofile",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="foto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="signup.profileimage",
            ),
        ),
    ]
