# Generated by Django 4.1.7 on 2023-04-14 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="url",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
