# Generated by Django 4.1.7 on 2023-05-18 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_kategori_alter_artikel_kategori"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="artikel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="blog.artikel",
            ),
        ),
    ]
